### ISSUE TITLE
List modules installed on server

### ISSUE THREAD

**Issue by Kevnz** [matthewfl/node-host#1]
It would be great if you could list any installed modules on the server.

**Comment by matthewfl** [comment]
Right now the modules are listed in the wiki
https://github.com/matthewfl/node-host/wiki/Api

You can also load in modules from your file system using require('./some_name')

As for modules being installed on the server, I am trying to keep it minimal so that users can support their own modules, there will also be support for requiring in code from other users soon and this should also address this issue
