### ISSUE TITLE
Allow watchFile, stat, any others that are safe -- instant live on deploy

### ISSUE THREAD

**Issue by ghost** [matthewfl/node-host#12]
Would be nice to be able to watch static assets and have edits go live automatically.

**Comment by matthewfl** [comment]
For deploy, the code goes live within 7 minutes when under heavy load.  And if the production url has not been hit for at least the last 5 minutes, then it will go live instantly.  (it just check if it has changed every 7 minutes).

As for file system, it is based off the same backing as the database.  And thus there would be no good way to watch a file without re-pinging the database every few seconds.  Also because the applications themselves can not modify the database, these files should not really be changing that much.

**Comment by ghost** [comment]
Okay, nvm :) misunderstood how things where working.
